# Generated by Django 3.2.4 on 2021-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='pincode',
            field=models.IntegerField(default=False),
        ),
    ]
