# Generated by Django 3.2.4 on 2021-07-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_auto_20210727_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='products',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
