# Generated by Django 3.2.4 on 2021-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0005_cartitem_linetotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='linetotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
